# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160802_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': (('can_vote', 'Whether a user can vote or not on polls.'), ('can_view', 'Can the user view?'))},
        ),
    ]
